export * from './apiGestionDeStockCommandefournisseur.service';
import { ApiGestionDeStockCommandefournisseurService } from './apiGestionDeStockCommandefournisseur.service';
export * from './authentification.service';
import { AuthentificationService } from './authentification.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './commandesClients.service';
import { CommandesClientsService } from './commandesClients.service';
export * from './entreprises.service';
import { EntreprisesService } from './entreprises.service';
export * from './fournisseur.service';
import { FournisseurService } from './fournisseur.service';
export * from './gestionDesArticles.service';
import { GestionDesArticlesService } from './gestionDesArticles.service';
export * from './gestionDesPhotos.service';
import { GestionDesPhotosService } from './gestionDesPhotos.service';
export * from './mouvementsDeStock.service';
import { MouvementsDeStockService } from './mouvementsDeStock.service';
export * from './utilisateurs.service';
import { UtilisateursService } from './utilisateurs.service';
export * from './ventes.service';
import { VentesService } from './ventes.service';
export const APIS = [ApiGestionDeStockCommandefournisseurService, AuthentificationService, CategoriesService, ClientsService, CommandesClientsService, EntreprisesService, FournisseurService, GestionDesArticlesService, GestionDesPhotosService, MouvementsDeStockService, UtilisateursService, VentesService];
