/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Categorie } from './categorie';
import { LigneVente } from './ligneVente';
import { MvtStk } from './mvtStk';
import { LigneCommandeClient } from './ligneCommandeClient';
import { LigneCommandeFournisseur } from './ligneCommandeFournisseur';


export interface Article { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    codeArticle?: string;
    designation?: string;
    prixUnitaireHt?: number;
    tauxTva?: number;
    prixUnitaireTtc?: number;
    photo?: string;
    idEntreprise?: number;
    categorie?: Categorie;
    ligneVentes?: Array<LigneVente>;
    ligneCommandeClients?: Array<LigneCommandeClient>;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseur>;
    mvtStks?: Array<MvtStk>;
}

