/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategorieDto } from './categorieDto';


export interface ArticleDto { 
    id?: number;
    codeArticle?: string;
    designation?: string;
    prixUnitaireHt?: number;
    tauxTva?: number;
    prixUnitaireTtc?: number;
    photo?: string;
    categorie?: CategorieDto;
    idEntreprise?: number;
}

