/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';


export interface Categorie { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    code?: string;
    designation?: string;
    idEntreprise?: number;
    articles?: Array<Article>;
}

