/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { CommandeClient } from './commandeClient';


export interface Client { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    nom?: string;
    prenom?: string;
    adresse?: Adresse;
    photo?: string;
    mail?: string;
    numTel?: string;
    idEntreprise?: number;
    commandeClients?: Array<CommandeClient>;
}

