/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Fournisseur } from './fournisseur';
import { LigneCommandeFournisseur } from './ligneCommandeFournisseur';


export interface CommandeFournisseur { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseurEtatCommandeEnum;
    idEntreprise?: number;
    fournisseur?: Fournisseur;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseur>;
}
export enum CommandeFournisseurEtatCommandeEnum {
    enPreparation = 'EN_PREPARATION',
    validee = 'VALIDEE',
    livree = 'LIVREE'
};



