/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeClient } from './ligneCommandeClient';
import { Client } from './client';


export interface CommandeClient { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeClientEtatCommandeEnum;
    idEntreprise?: number;
    client?: Client;
    ligneCommandeClients?: Array<LigneCommandeClient>;
}
export enum CommandeClientEtatCommandeEnum {
    enPreparation = 'EN_PREPARATION',
    validee = 'VALIDEE',
    livree = 'LIVREE'
};



