/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeFournisseurDto } from './ligneCommandeFournisseurDto';
import { FournisseurDto } from './fournisseurDto';


export interface CommandeFournisseurDto { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseurDtoEtatCommandeEnum;
    fournisseur?: FournisseurDto;
    idEntreprise?: number;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseurDto>;
    commandeLivree?: boolean;
}
export enum CommandeFournisseurDtoEtatCommandeEnum {
    enPreparation = 'EN_PREPARATION',
    validee = 'VALIDEE',
    livree = 'LIVREE'
};



