/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientDto } from './clientDto';
import { LigneCommandeClientDto } from './ligneCommandeClientDto';


export interface CommandeClientDto { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeClientDtoEtatCommandeEnum;
    client?: ClientDto;
    idEntreprise?: number;
    ligneCommandeClients?: Array<LigneCommandeClientDto>;
    commandeLivree?: boolean;
}
export enum CommandeClientDtoEtatCommandeEnum {
    enPreparation = 'EN_PREPARATION',
    validee = 'VALIDEE',
    livree = 'LIVREE'
};



