/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';
import { CommandeFournisseur } from './commandeFournisseur';


export interface LigneCommandeFournisseur { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    article?: Article;
    commandeFournisseur?: CommandeFournisseur;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
}

