/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeFournisseur } from './commandeFournisseur';
import { ArticleDto } from './articleDto';


export interface LigneCommandeFournisseurDto { 
    id?: number;
    article?: ArticleDto;
    commandeFournisseur?: CommandeFournisseur;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
}

