/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Ventes } from './ventes';
import { Article } from './article';


export interface LigneVente { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    vente?: Ventes;
    article?: Article;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
}

