/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VentesDto } from './ventesDto';
import { ArticleDto } from './articleDto';


export interface LigneVenteDto { 
    id?: number;
    vente?: VentesDto;
    article?: ArticleDto;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
}

