/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Article } from './article';


export interface MvtStk { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    dateMvt?: string;
    quantite?: number;
    article?: Article;
    typeMvt?: MvtStkTypeMvtEnum;
    sourceMvt?: MvtStkSourceMvtEnum;
    idEntreprise?: number;
}
export enum MvtStkTypeMvtEnum {
    entree = 'ENTREE',
    sortie = 'SORTIE',
    correctionPos = 'CORRECTION_POS',
    correctionNeg = 'CORRECTION_NEG'
};
export enum MvtStkSourceMvtEnum {
    commandeClient = 'COMMANDE_CLIENT',
    commandeFournisseur = 'COMMANDE_FOURNISSEUR',
    vente = 'VENTE'
};



