/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface MvtStkDto { 
    id?: number;
    dateMvt?: string;
    quantite?: number;
    article?: ArticleDto;
    typeMvt?: MvtStkDtoTypeMvtEnum;
    sourceMvt?: MvtStkDtoSourceMvtEnum;
    idEntreprise?: number;
}
export enum MvtStkDtoTypeMvtEnum {
    entree = 'ENTREE',
    sortie = 'SORTIE',
    correctionPos = 'CORRECTION_POS',
    correctionNeg = 'CORRECTION_NEG'
};
export enum MvtStkDtoSourceMvtEnum {
    commandeClient = 'COMMANDE_CLIENT',
    commandeFournisseur = 'COMMANDE_FOURNISSEUR',
    vente = 'VENTE'
};



