/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVenteDto } from './ligneVenteDto';


export interface VentesDto { 
    id?: number;
    code?: string;
    dateVente?: string;
    commentaire?: string;
    ligneVentes?: Array<LigneVenteDto>;
    idEntreprise?: number;
}

