/**
 * Gestion de stock Rest API
 *
 * Contact: your.email@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVente } from './ligneVente';


export interface Ventes { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    code?: string;
    dateVente?: string;
    commentaire?: string;
    idEntreprise?: number;
    ligneVentes?: Array<LigneVente>;
}

